### ISSUE TITLE
Add section on README.md on how to deploy on a production server

### ISSUE THREAD

**Issue by nikolas-n** [perseids-project/lsj-js#11]
Hi there,

Fantastic repo, thanks a lot! I'm interested in deploying it on a production server. Could you give some guidance please?

Thanks again!

(not a proper issue but didn't know where to mention it... sorry)

**Comment by zfletch** [comment]
I do think it makes sense to include some deployment information in the README. What information would you need or would you find helpful in order to deploy it?

Since it's JavaScript app, you should be able to build it then serve the static assets using any web server. The one difficulty is that you need to change the `PUBLIC_URL` depending on the path.

For example, if you're deploying it to `whatever.com/`, you can run `PUBLIC_URL='./' yarn build` and then use the assets in the `build/` folder. However, if you're deploying it to `whatever.com/apps/lsj/`, you would need to run `PUBLIC_URL=./apps/lsj/ yarn build`.

**Comment by nikolas-n** [comment]
Thanks, it worked! I just run `PUBLIC_URL='./' yarn build` and it works. Maybe, if you have time, you could add your response to my comment into the README.md. I believe it'll be sufficient for anyone who is not familiar with yarn and wants to get a production build of your application (just like me).

**Comment by chopinesque** [comment]
Is it possible to run it locally on Windows 10, or even in AMPPS? Not sure of the procedure. I tried installing https://yarnpkg.com/lang/en/docs/install/#windows-stable and then running and https://nodejs.org/en/download/ but no luck with **yarn test**, I got:

```
yarn run v1.13.0
$ react-app-rewired test --env=jsdom
'react-app-rewired' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

```

**Comment by zfletch** [comment]
@chopinesque I don't see why it wouldn't run on Windows. Have you run `yarn install` before running `yarn test`?

**Comment by chopinesque** [comment]
Let me get this right; I installed Node.js and I get now on its cmd:
```
Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        7.503s
Ran all test suites.

Watch Usage: Press w to show more.
```
How do I actually make a search on my machine? Excuse my ignorance.

**Comment by zfletch** [comment]
@chopinesque It looks like you have tests passing locally, which is good news. It means everything is installed correctly. If you would like to run a development server locally, the command you want to run is `yarn start` (not `yarn test`). After running `yarn start`, you can use the application locally by visiting `http://localhost:3000/` in a web browser.

If you would like to create a production version of the application and serve it with a web server, the command you want to run in `PUBLIC_URL='/' yarn build`. You may need to change `/` if you are going to serve the application on a different path (see README.md). This command will create static HTML and JavaScript files in the `./build` directory that you can serve directly with the web server of your choice.

This application is built on top of Create React App. If you'd like more information about how it works, I'd recommend checking out [their documentation](https://facebook.github.io/create-react-app/docs/getting-started) as well.
