### ISSUE TITLE
Markup tag left in description

### ISSUE THREAD

**Issue by wmotte** [perseids-project/lsj-js#8]
In some entries there is an '&amp' markup tag left in the description. E.g. at ἀκμάζω:

ἔχεσθαι **&apos;**tis time to . ., A.Th.97 (lyr.)

This should be rendered as a single apostrophe. I.e. " 'tis time to. . "

**Comment by zfletch** [comment]
Great catch. I wrote a fix for that issue in https://github.com/perseids-project/lsj-js/pull/9
